version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: spurilo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: spurilo

  mongo-express:
    image: mongo-express:latest
    container_name: spurilo-mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false